
language: python
python:
  - "3.5"

script:
  python ./tools/export_mod.py

before_deploy:
  sh ./tools/deploy.sh

deploy:
  provider: releases
  api_key: "$AUTH_TOKEN"
  file: 
    - "Russian.pak"
    - "Russian.zip"
  skip_cleanup: true
  on:
    tags: true
    branch: master
